services:
  postgres:
    container_name: pet-family-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=petfamily
    ports:
      - 5432:5432
    volumes:
      - pet-family_data:/var/lib/postgresql/data

  seq:
     container_name: seq
     image: datalust/seq:latest
     restart: always
     environment:
       - ACCEPT_EULA=Y
     ports: 
       - 5341:5341
       - 8081:80

  minio:
     container_name: pet-family-minio
     image: minio/minio
     restart: always
     ports:
        - 9000:9000
        - 9001:9001
     command: server --console-address ":9001" /data
     volumes:
     - pet-family_minio_data:/data
     - pet-family_minio_data:/logs 
     environment:
         MINIO_ROOT_USER: minioadmin
         MINIO_ROOT_PASSWORD: minioadmin
         MINIO_LOGGER: console 
         MINIO_LOGGER_HTTP_TRACE: /data/logs/minio-http.log
      
volumes:
  pet-family_data:
  pet-family_minio_data: