services:
  postgres:
    container_name: pet-family-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=petfamily
    ports:
      - 5432:5432
    volumes:
      - pet-family_data:/var/lib/postgresql/data

  seq:
     container_name: seq
     image: datalust/seq:latest
     restart: always
     environment:
       - ACCEPT_EULA=Y
     ports: 
       - 5341:5341
       - 8081:80
