services:
  postgres:
    container_name: pet-family-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=petfamily
    ports:
      - "5432:5432"
    volumes:
      - pet-family_data:/var/lib/postgresql/data

