services:
  postgres:
    container_name: pet-family-postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=petfamilydb
    ports:
      - 5433:5432
    volumes:
      - petfamily1_data:/var/lib/postgresql/data
    networks:
      - pet-family-network

  seq:
    container_name: seq
    image: datalust/seq:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
    networks:
      - pet-family-network

  minio:
    container_name: pet-family-minio
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    command: server --console-address ":9001" /data
    volumes:
      - pet-family_minio_data:/data
      - pet-family_minio_data:/logs
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_LOGGER: console
      MINIO_LOGGER_HTTP_TRACE: /data/logs/minio-http.log
    networks:
      - pet-family-network

volumes:
  petfamily1_data:
  pet-family_minio_data:

networks:
  pet-family-network:
    driver: bridge
